#165305764 Favoriting an article
andela/ah-the-immortals-backend pull request #41
Opened 2019-05-08 09:30 UTC by a-braham

### What does this PR do?
- Allows users to favorite an article
### What are the tasks to be completed?
* Ensure that a user can be able to post a favorite
* Ensure a user can be able to remove an article from favorites
* Ensure that user can be able to get his favorite articles
### How can this be manually tested?
 **After cloning the repo:-**
```
$ git checkout  ft-favorite-articles-165305764
$ python manage.py runserver
```
b. **Test with postman**
1. After signing up a user, login grub the token and add it to authorization:
```
POST /api/articles/{slug}/favorite
```
click send

### What are the relevant pivotal tracker stories?
[#165305764](https://www.pivotaltracker.com/n/projects/2326460/stories/165305764)

### Screenshots
<img width="1440" alt="Screenshot 2019-05-08 at 12 28 14" src="https://user-images.githubusercontent.com/45788436/57365023-f87fdc80-718c-11e9-884d-ded133d0e3c7.png">
<img width="1440" alt="Screenshot 2019-05-08 at 12 28 26" src="https://user-images.githubusercontent.com/45788436/57365024-f87fdc80-718c-11e9-9441-3594734bd4b4.png">

2019-05-08 09:54 UTC, Bakley commented
@a-braham  Kindly add **How to run test** on your PR descriptions. It will help new users know what to do to see the test passing locally

2019-05-09 06:41 UTC, matthenge requested changes
@a-braham  Please update the PR comment to reflect the delete endpoint. Also, change the screenshot for the delete endpoint to reflect the current one

2019-05-09 07:08 UTC, Ogutu-Brian requested changes

2019-05-09 07:08 UTC, Ogutu-Brian commented on authors/apps/articles/views.py
> +from django.shortcuts import render
Hello @a-braham ,
You are not using this module, so you don't need to import it

2019-05-09 17:53 UTC, Ogutu-Brian requested changes

2019-05-09 17:53 UTC, Ogutu-Brian commented on authors/apps/articles/tests/test_favorite.py
> +
Hello @a-braham ,
Please add a new line at the end of file

2019-05-09 21:50 UTC, matthenge approved these changes
LGTM

2019-05-09 23:07 UTC, IssaIan approved these changes
LGTM

2019-05-10 08:03 UTC, merged