#166027202 User can delete a specific notification
andela/ah-the-immortals-backend pull request #66
Opened 2019-05-15 09:27 UTC by IssaIan

### What does this PR do?
- Implement deletion of a specific notification
### What are the tasks to be completed?
* Create endpoint to enable user to delete a single notification
* Write tests for the implementation
### How can this be manually tested?
### Local Development Setup
Refer to the project [Readme.md](https://github.com/andela/ah-the-immortals-backend) for this.
**Test with postman**
1. Signing up two users and verify
2. Follow one user: 
```
POST  http://127.0.0.1:8000/api/profiles/<*username*>/follow/
```
3. Create an article using the followed user:
```
POST http://127.0.0.1:8000/api/articles/
```
4. Fetch the following-user notifications using:
```
GET http://127.0.0.1:8000/api/notifications/
```
5. Send a delete request to the following url using the correct parameters with the following-user:
```
DELETE **http://127.0.0.1:8000/api/notifications/<*id*>/
```
**Screenshots**
![image](https://user-images.githubusercontent.com/41931013/57764710-abf84c00-770c-11e9-8e3e-aec357bbed2a.png)
![image](https://user-images.githubusercontent.com/41931013/57764740-badefe80-770c-11e9-8047-9e501554f9fc.png)

### What are the relevant pivotal tracker stories?
[##166027202](https://www.pivotaltracker.com/n/projects/2326460/stories/166027202)

2019-05-15 10:25 UTC, Ogutu-Brian approved these changes

2019-05-15 17:23 UTC, Ogutu-Brian requested changes
Hello @IssaIan ,
You could consider changing the **from mail** from **apikey**  to *noreply@authorsheaven.com* since that is the address we are using for other emails. This would enhance uniformity in our application

2019-05-16 06:02 UTC, IssaIan commented
> Hello @IssaIan ,
> You could consider changing the **from mail** from **apikey** to _[noreply@authorsheaven.com](mailto:noreply@authorsheaven.com)_ since that is the address we are using for other emails. This would enhance uniformity in our application



> Hello @IssaIan ,
> You could consider changing the **from mail** from **apikey** to _[noreply@authorsheaven.com](mailto:noreply@authorsheaven.com)_ since that is the address we are using for other emails. This would enhance uniformity in our application

Done

2019-05-16 06:18 UTC, Ogutu-Brian approved these changes
LGTM

2019-05-16 10:28 UTC, merged