#165305741 Write tests for existing user features(Register, Login, Update, Retrieve)
andela/ah-the-immortals-backend pull request #7
Opened 2019-04-23 21:35 UTC by a-braham

#### Description
Initially the existing features(Register users, login, update, and retrieve) were not tested. This chore writes unit tests for these features to test whether the features work as required and what can be added to these features.

#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [ ] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [ ] End to end
- [ ] Integration
- [ ] Unit tests

#### Checklist:
- [ ] My code follows the style guide for this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

#### Pivotal Tracker
[165305741](https://www.pivotaltracker.com/n/projects/2326460/stories/165305741)

2019-04-24 05:06 UTC, mdn-network requested changes
You have pushed commented code

2019-04-24 06:43 UTC, Bakley commented
> You have pushed commented code

@Philipotieno Could you be more specific to which lines of code were commented so that @a-braham can have an easy time to figure it out. :-)

2019-04-24 08:00 UTC, Ogutu-Brian requested changes

2019-04-24 08:00 UTC, Ogutu-Brian commented on authors/apps/authentication/tests/basetests.py
> +    client = APIClient
Hello @a-braham ,
Can you use APIClient object instead by instantiating the APIClient class. This would allow accessibility of instance methods too. Currently, you can only use static and class methods of the APIClient class.

2019-04-24 12:08 UTC, mdn-network approved these changes

2019-04-24 12:15 UTC, IssaIan approved these changes
LGTM

2019-04-24 12:24 UTC, Ogutu-Brian requested changes

2019-04-24 12:24 UTC, Ogutu-Brian commented on authors/apps/authentication/tests/test_users.py
> +        # self.assertEqual(response.data, 'You have been logged out')
Hello @a-braham ,
Would you please remove the commented code

2019-04-24 12:39 UTC, Ogutu-Brian approved these changes
LGTM

2019-04-24 12:48 UTC, matthenge commented on authors/apps/authentication/tests/test_users.py
> +        response = self.get_user()
@a-braham please add a blank line at the end of the file to conform to pep8 standards

2019-04-24 12:51 UTC, matthenge requested changes

2019-04-24 12:51 UTC, matthenge commented on authors/apps/authentication/tests/test_users.py
> +        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
@a-braham please add a blank line at the end of the file to conform to pep8 standards

2019-04-24 13:01 UTC, matthenge approved these changes

2019-04-24 13:02 UTC, matthenge reviewed
LGTM

2019-04-25 07:35 UTC, Amoswachira approved these changes
LGTM

2019-04-25 11:18 UTC, merged