#166843575 Fix rating of articles
andela/ah-the-immortals-backend pull request #81
Opened 2019-06-21 14:05 UTC by Philipotieno

#### What does this PR do?
 -  Fix rating of articles
#### Description of Task to be completed?
- Get average ratings on an articles
- Get ratings for different users
- Get average ratings only when the user is not logged in
#### How should this be manually tested?
- `$ git clone https://github.com/andela/ah-the-immortals-backend.git`
- `$ git fetch origin` - To get all branches
- `$ ft-like-comments-165305776`
- Create a virtual environment and activate it
        `$ python3.7 venv venv`
        ` $ source venv/bin/activate`
- Add a .env file as in the .env.example
        `$ source .env`
- ` $ pip intsall -r requirements.txt`

`$ psql postgres`
`postgres=# CREATE USER your-user WITH PASSWORD 'your-password';`
`postgres=# ALTER ROLE your-user SET client_encoding TO 'utf8';`
`postgres=# ALTER ROLE your-user SET default_transaction_isolation TO 'read committed';`
`postgres=# ALTER ROLE your-user SET timezone TO 'UTC';`
`postgres=# CREATE DATABASE your-database-name;`
`postgres=# GRANT ALL PRIVILEGES ON DATABASE your-database-name TO your-user;`
`postgres=# \q`
- Start server ` $ python manage.py runserver`
- Test the following endpoints on postman
   - Rate an article `POST http:/api/articles/{slug}/rate/`
   - Get an article `GET http:/api/articles/{slug}/`
- Run tests ` $ python api/manage.py test`
#### What are the relevant pivotal tracker stories?
[#166843575](https://www.pivotaltracker.com/n/projects/2326460/stories/166843575)
#### Screenshots

#### Authenticated
![image](https://user-images.githubusercontent.com/29012135/59928028-831f5100-9446-11e9-9703-a6bea11f7c3c.png)

#### Not - Authenticated
![image](https://user-images.githubusercontent.com/29012135/59928016-78fd5280-9446-11e9-8db0-e61a5ef99dc5.png)

2019-06-21 14:08 UTC, Amoswachira approved these changes

2019-06-22 12:17 UTC, Ogutu-Brian approved these changes

2019-06-24 07:42 UTC, Bakley approved these changes

2019-06-25 08:36 UTC, matthenge approved these changes
LGTM

2019-06-25 09:25 UTC, charisschomba requested changes

2019-06-25 09:25 UTC, charisschomba commented on authors/apps/articles/views.py
>              ]
Remove this comment

2019-06-25 09:32 UTC, Philipotieno commented on authors/apps/articles/views.py
>              ]
Done @charisschomba

2019-06-25 11:16 UTC, merged